---
title: "ChromRatesEvolCarex"
author: "Marcial Escudero"
date: "7/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

Setting up the data set

```{r}
PPAbio <- read.csv("PPAbio.csv")
PPAbio <- PPAbio[,2:6]
colnames(PPAbio) <- c("species", "RB1", "RB4", "RB7", "RB12")
PPAbio

PPAculm <- read.csv("PPAculm.csv")
PPAculm <- PPAculm[,2:3]
colnames(PPAculm) <- c("species", "RCU")
PPAculm

PPALateralInfl <- read.csv("PPALateralInfl.csv")
PPALateralInfl <- PPALateralInfl[,2:3]
colnames(PPALateralInfl) <- c("species", "RLI")
PPALateralInfl

PPAdiv2n <- read.csv("PPAdiv2n.csv")
PPAdiv2n <- PPAdiv2n[,2:6]
colnames(PPAdiv2n) <- c("species", "SP", "EX", "DI", "R2n")
PPAdiv2n


PPAmorph <- merge(PPAculm, PPALateralInfl, by.x = "species", by.y= "species", all = T)
PPAmorph

dim(PPAculm)
dim(PPALateralInfl)
dim(PPAmorph)

PPAmorphbio <- merge(PPAmorph, PPAbio, by.x = "species", by.y= "species", all = T)
dim(PPAmorphbio)

PPAdata <- merge(PPAmorphbio, PPAdiv2n, by.x = "species", by.y= "species", all = T)
dim(PPAdata)


```

Starting analyses with phylopath

```{r}

library(ape)
my_tree <- read.tree('Carex2n.tree') # For Newick format trees

my_data <- PPAdata
rownames(my_data) <- my_data$species

#my_tree$tip.label # Check the tip labels of your tree
#rownames(my_data) <- gsub(' ', '_', my_data$species_name_with_spaces)

library(phylopath)

models <- define_model_set(
  null = c(),
  
  #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n  = c(DI ~ R2n),
  rmor.r2n = c(RCU ~ R2n,RLI ~ R2n),
  d.r2n..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n),
  d.r2n..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4),
  rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4),
  d.r2n..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4),
   
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rmor  = c(DI ~ R2n,DI ~ RCU + RLI),
  d.rmor..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI),
  d.r2n..d.rmor..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI),
  d.r2n..d.rmor..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  d.rmor..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  d.r2n..d.rmor..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rbio  = c(DI ~ R2n, DI ~ RB4),
  d.rbio..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n, DI ~ RB4),
  d.r2n..d.rbio..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, DI ~ RB4),
  d.r2n..d.rbio..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4, DI ~ RB4),
  d.rbio..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4),
  d.r2n..d.rbio..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4),
  
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rmor..d.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  
 #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..rmor.rbio  = c(DI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
   
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rmor..rmor.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rbio..rmor.rbio  = c(DI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rmor..d.rbio..rmor.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4), 
 
  .common = c()
)


models$d.r2n

plot(models$d.r2n)

plot_model_set(models)

result <- phylo_path(models, data = my_data, tree = my_tree, model = 'lambda', na.rm = TRUE)

result

(s <- summary(result))

plot(s)

(best_model <- best(result))


plot(best_model)

average_model <- average(result)
average_model
plot(average_model, algorithm = 'mds', curvature = 0.1) # increase the curvature to avoid overlapping edges

average_model_full <- average(result, avg_method = "full")
average_model_full
plot(average_model_full, algorithm = 'mds', curvature = 0.1)





```


Let's make the models onky with the variables, no rates!

```{r}
culm <- read.csv("./traits/data_culm.csv", sep = ";")
LateralInfl <- read.csv("./traits/data_LateralInfl.csv", sep = ";")
chr2n <- read.csv("./traits/data_2n.csv", sep = "")
bio1 <- read.csv("./traits/data_bio1.csv", sep = ";")
bio4 <- read.csv("./traits/data_bio4.csv", sep = ";")
bio7 <- read.csv("./traits/data_bio7.csv", sep = ";")
bio12 <- read.csv("./traits/data_bio12.csv", sep = ";")

morph <- merge(culm, LateralInfl, by.x = "original.name", by.y= "original.name", all = T)
morph
bio14 <- merge(bio1, bio4, by.x = "original.name", by.y= "original.name", all = T)
bio147 <- merge(bio14, bio7, by.x = "original.name", by.y= "original.name", all = T)
bio <- merge(bio147, bio12, by.x = "original.name", by.y= "original.name", all = T)

morphbio <- merge(morph, bio, by.x = "original.name", by.y= "original.name", all = T)

data <- merge(morphbio, chr2n, by.x = "original.name", by.y= "original.name", all = T)
dim(data)

names(PPAdata) <- c("species", "RCU", "RLI", "RB1", "RB4", "RB7", "RB12", "SP", "EX", "DI", "R2n") 
names(data) <- c("species", "CU", "LI", "B1", "B4", "B7","B12",  "C2n")
PPAdata <- merge(PPAdata, data, by.x = "species", by.y= "species", all = T)
names(PPAdata)

write.csv(PPAdata, file="PPAdata.csv")
plot(PPAdata$R2n ~ PPAdata$C2n)
summary(lm(PPAdata$R2n ~ PPAdata$C2n))


library(ape)
my_tree <- read.tree('Carex2n.tree') # For Newick format trees

my_data2 <- PPAdata
rownames(my_data2) <- my_data2$species

#my_tree$tip.label # Check the tip labels of your tree
#rownames(my_data) <- gsub(' ', '_', my_data$species_name_with_spaces)

library(phylopath)

modelsnorates <- define_model_set(
  null = c(),
  
  #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n  = c(DI ~ C2n),
  mor.2n = c(CU ~ C2n,LI ~ C2n),
  d.2n..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n),
  d.2n..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
  mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
   
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.mor  = c(DI ~ C2n,DI ~ CU + LI),
  d.mor..mor.2n = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI),
  d.2n..d.mor..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n,DI ~ CU + LI),
  d.2n..d.mor..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  d.mor..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  d.2n..d.mor..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.bio  = c(DI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n = c(CU ~ C2n,LI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.mor..d.bio  = c(DI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..mor.bio  = c(DI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
   
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.mor..mor.bio  = c(DI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.bio..mor.bio  = c(DI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.mor..d.bio..mor.bio  = c(DI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio.mor.2n..mor.bio = c(CU ~ C2n, LI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12), 

  .common = c()
  
)

modelsnorates$d.2n

plot(modelsnorates$d.2n)

plot_model_set(modelsnorates)

resultnorates <- phylo_path(modelsnorates, data = my_data2, tree = my_tree, model = 'lambda', na.rm = TRUE)

resultnorates

(snorates <- summary(resultnorates))
plot(snorates)

(best_modelnorates <- best(resultnorates))


plot(best_modelnorates)

average_modelnorates <- average(resultnorates)
average_modelnorates
plot(average_modelnorates, algorithm = 'mds', curvature = 0.2) # increase the curvature to avoid overlapping edges

average_model_fullnorates <- average(resultnorates, avg_method = "full")
average_model_fullnorates
plot(average_model_fullnorates, algorithm = 'mds', curvature = 0.2)


#We are going to repeat the process but excluding Spiros from NZ
my_data3 <- PPAdata
rownames(my_data3) <- my_data3$species
my_data3$DI[my_data3$DI > 3.5] <- NA

plot(my_data2$DI ~ my_data2$C2n)
summary(lm(my_data2$DI ~ my_data2$C2n))
plot(my_data3$DI ~ my_data3$C2n)
summary(lm(my_data3$DI ~ my_data3$C2n))

resultnorates2 <- phylo_path(modelsnorates, data = my_data3, tree = my_tree, model = 'lambda', na.rm = TRUE)

resultnorates2

(snorates2 <- summary(resultnorates2))
plot(snorates2)

(best_modelnorates2 <- best(resultnorates2))


plot(best_modelnorates2)

average_modelnorates2 <- average(resultnorates2)
average_modelnorates2
plot(average_modelnorates2, algorithm = 'mds', curvature = 0.2) # increase the curvature to avoid overlapping edges

average_model_fullnorates2 <- average(resultnorates2, avg_method = "full")
average_model_fullnorates2
plot(average_model_fullnorates2, algorithm = 'mds', curvature = 0.2)

library(caper)
comparative.data1 <- comparative.data(my_tree, my_data2[,c(1,10,18)], species, vcv=TRUE, vcv.dim=3)
comparative.data1
mod1 <- pgls(DI ~ C2n, comparative.data1, lambda='ML')
summary(mod1)

comparative.data2 <- comparative.data(my_tree, my_data3[,c(1,10,18)], species, vcv=TRUE, vcv.dim=3)
comparative.data2
mod2 <- pgls(DI ~ C2n, comparative.data2, lambda='ML')
summary(mod2)

```


Let´s make more complex models with chromosome numbers and bios and morphological variables and rates

```{r}



models3 <- define_model_set(
  null = c(),
  
  #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n  = c(DI ~ R2n),
  rmor.r2n = c(RCU ~ R2n,RLI ~ R2n),
  d.r2n..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n),
  d.r2n..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4),
  rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4),
  d.r2n..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4),
   
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rmor  = c(DI ~ R2n,DI ~ RCU + RLI),
  d.rmor..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI),
  d.r2n..d.rmor..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI),
  d.r2n..d.rmor..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  d.rmor..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  d.r2n..d.rmor..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI),
  
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rbio  = c(DI ~ R2n, DI ~ RB4),
  d.rbio..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n, DI ~ RB4),
  d.r2n..d.rbio..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, DI ~ RB4),
  d.r2n..d.rbio..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4, DI ~ RB4),
  d.rbio..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4),
  d.r2n..d.rbio..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4),
  
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.rmor..d.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.r2n = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..r2n.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.r2n.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  
 #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..rmor.rbio  = c(DI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
   
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rmor..rmor.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rbio..rmor.rbio  = c(DI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rbio..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.rmor..d.rbio..rmor.rbio  = c(DI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.r2n..rmor.rbio = c(RCU ~ R2n,RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..r2n.rbio..rmor.rbio  = c(DI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.r2n.rbio..rmor.rbio = c(RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.r2n..d.rmor..d.rbio..rmor.r2n.rbio..rmor.rbio = c(DI ~ R2n, RCU ~ R2n ,  RLI ~ R2n, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4), 
 
 
  #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n  = c(DI ~ C2n),
  mor.2n = c(CU ~ C2n,LI ~ C2n),
  d.2n..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n),
  d.2n..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
  mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12),
   
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.mor  = c(DI ~ C2n,DI ~ CU + LI),
  d.mor..mor.2n = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI),
  d.2n..d.mor..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n,DI ~ CU + LI),
  d.2n..d.mor..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  d.mor..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  d.2n..d.mor..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.bio  = c(DI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n = c(CU ~ C2n,LI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.mor..d.bio  = c(DI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..2n.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..mor.bio  = c(DI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
   
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.mor..mor.bio  = c(DI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.bio..mor.bio  = c(DI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n..mor.bio = c(CU ~ C2n,LI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.bio..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.mor..d.bio..mor.bio  = c(DI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio.mor.2n..mor.bio = c(CU ~ C2n, LI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n..mor.bio = c(DI ~ C2n, CU ~ C2n ,  LI ~ C2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..2n.bio..mor.bio  = c(DI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.2n.bio..mor.bio = c(CU ~ C2n ,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.2n..d.mor..d.bio..mor.2n.bio..mor.bio = c(DI ~ C2n, CU ~ C2n,  LI ~ C2n, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12), 

  #Consider always both C2n + R2n
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n  = c(DI ~ C2n + R2n),
  mor.b2n = c(CU ~ C2n + R2n,LI ~ C2n + R2n),
  d.b2n..mor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n),
  d.b2n..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12),
  mor.b2n.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12),
  d.b2n..mor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12),
   
  #Consider always both C2n + R2n
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.mor  = c(DI ~ C2n + R2n,DI ~ CU + LI),
  d.mor..mor.b2n = c(CU ~ C2n + R2n,LI ~ C2n + R2n,DI ~ CU + LI),
  d.b2n..d.mor..mor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n,DI ~ CU + LI),
  d.b2n..d.mor..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI),
  d.mor..mor.b2n.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI),
  d.b2n..d.mor..mor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  
 #Consider always both C2n + R2n
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.bio  = c(DI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.b2n = c(CU ~ C2n + R2n,LI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..mor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.b2n.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..mor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  
 #Consider always both C2n + R2n
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.mor..d.bio  = c(DI ~ C2n + R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.b2n = c(CU ~ C2n + R2n,LI ~ C2n + R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..mor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.b2n.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..mor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),

#Consider always both C2n + R2n  
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..mor.bio  = c(DI ~ C2n + R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.b2n..mor.bio = c(CU ~ C2n + R2n,LI ~ C2n + R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..mor.b2n..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..b2n.bio..mor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.b2n.bio..mor.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..mor.b2n.bio..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
 
#Consider always both C2n + R2n
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.mor..mor.bio  = c(DI ~ C2n + R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.b2n..mor.bio = c(CU ~ C2n + R2n,LI ~ C2n + R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..mor.b2n..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n,  LI ~ C2n + R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..b2n.bio..mor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.b2n.bio..mor.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..mor.b2n.bio..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
#Consider always both C2n + R2n
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.bio..mor.bio  = c(DI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.b2n..mor.bio = c(CU ~ C2n + R2n,LI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..mor.b2n..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..b2n.bio..mor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.b2n.bio..mor.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.bio..mor.b2n.bio..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
#Consider always both C2n + R2n
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.mor..d.bio..mor.bio  = c(DI ~ C2n + R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio.mor.b2n..mor.bio = c(CU ~ C2n + R2n, LI ~ C2n + R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..mor.b2n..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n ,  LI ~ C2n + R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..b2n.bio..mor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.b2n.bio..mor.bio = c(CU ~ C2n + R2n ,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.b2n..d.mor..d.bio..mor.b2n.bio..mor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n,  LI ~ C2n + R2n, R2n ~ B1 + B4 + B7 + B12, C2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),    

#Consider always both C2n + R2n
#only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  #d.b2n  = c(DI ~ C2n + R2n),
  rmor.b2n = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n),
  d.b2n..rmor.b2n = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n),
  d.b2n..b2n.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4),
  rmor.b2n.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4),
  d.b2n..rmor.b2n.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4),
   
#Consider always both C2n + R2n
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.rmor  = c(DI ~ R2n + C2n,DI ~ RCU + RLI),
  d.rmor..rmor.b2n = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n,DI ~ RCU + RLI),
  d.b2n..d.rmor..rmor.b2n = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n,DI ~ RCU + RLI),
  d.b2n..d.rmor..b2n.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI),
  d.rmor..rmor.b2n.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI),
  d.b2n..d.rmor..rmor.b2n.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI),
  
#Consider always both C2n + R2n
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.rbio  = c(DI ~ R2n + C2n, DI ~ RB4),
  d.rbio..rmor.b2n = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n, DI ~ RB4),
  d.b2n..d.rbio..rmor.b2n = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, DI ~ RB4),
  d.b2n..d.rbio..b2n.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4),
  d.rbio..rmor.b2n.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4),
  d.b2n..d.rbio..rmor.b2n.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4),
  
#Consider always both C2n + R2n
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.rmor..d.rbio  = c(DI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.b2n = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.b2n..d.rmor..d.rbio..rmor.b2n = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.b2n..d.rmor..d.rbio..b2n.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.b2n.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.b2n..d.rmor..d.rbio..rmor.b2n.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  
#Consider always both C2n + R2n
 #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..rmor.rbio  = c(DI ~ R2n + C2n, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.b2n..rmor.rbio = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..rmor.b2n..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..b2n.rbio..rmor.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.b2n.rbio..rmor.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..rmor.b2n.rbio..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
   
#Consider always both C2n + R2n
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.rmor..rmor.rbio  = c(DI ~ R2n + C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.b2n..rmor.rbio = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..rmor.b2n..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..b2n.rbio..rmor.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.b2n.rbio..rmor.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..rmor.b2n.rbio..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  
#Consider always both C2n + R2n
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.rbio..rmor.rbio  = c(DI ~ R2n + C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.b2n..rmor.rbio = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rbio..rmor.b2n..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rbio..b2n.rbio..rmor.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.b2n.rbio..rmor.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rbio..rmor.b2n.rbio..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  
#Consider always both C2n + R2n
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.rmor..d.rbio..rmor.rbio  = c(DI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.b2n..rmor.rbio = c(RCU ~ R2n + C2n,RLI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..d.rbio..rmor.b2n..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..d.rbio..b2n.rbio..rmor.rbio  = c(DI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.b2n.rbio..rmor.rbio = c(RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.b2n..d.rmor..d.rbio..rmor.b2n.rbio..rmor.rbio = c(DI ~ R2n + C2n, RCU ~ R2n + C2n ,  RLI ~ R2n + C2n, C2n ~ RB4, R2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4), 


 #Consider always R2n but not C2n
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  #d.r2n  = c(DI ~ R2n),
  mor.r2n = c(CU ~ R2n,LI ~ R2n),
  d.r2n..mor.r2n = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n),
  d.r2n..r2n.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12),
  mor.r2n.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12),
  d.r2n..mor.r2n.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12),
   
  #Consider always R2n but not C2n
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.mor  = c(DI ~ R2n,DI ~ CU + LI),
  d.mor..mor.r2n = c(CU ~ R2n,LI ~ R2n,DI ~ CU + LI),
  d.r2n..d.mor..mor.r2n = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n,DI ~ CU + LI),
  d.r2n..d.mor..r2n.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI),
  d.mor..mor.r2n.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI),
  d.r2n..d.mor..mor.r2n.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI),
  
 #Consider always R2n but not C2n
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.bio  = c(DI ~ R2n, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.r2n = c(CU ~ R2n,LI ~ R2n, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..mor.r2n = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..r2n.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.bio..mor.r2n.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..mor.r2n.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12),
  
 #Consider always R2n but not C2n
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.r2n..d.mor..d.bio  = c(DI ~ R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.r2n = c(CU ~ R2n,LI ~ R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..mor.r2n = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..r2n.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.r2n.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..mor.r2n.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12),

#Consider always R2n but not C2n  
 #only variables, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..mor.bio  = c(DI ~ R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.r2n..mor.bio = c(CU ~ R2n,LI ~ R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..mor.r2n..mor.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..r2n.bio..mor.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  mor.r2n.bio..mor.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..mor.r2n.bio..mor.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
 
#Consider always R2n but not C2n
  #only variables, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.mor..mor.bio  = c(DI ~ R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.r2n..mor.bio = c(CU ~ R2n,LI ~ R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..mor.r2n..mor.bio = c(DI ~ R2n, CU ~ R2n,  LI ~ R2n,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..r2n.bio..mor.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.mor..mor.r2n.bio..mor.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..mor.r2n.bio..mor.bio = c(DI ~ R2n, CU ~ R2n,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12,DI ~ CU + LI, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
#Consider always R2n but not C2n
   #only variables, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.bio..mor.bio  = c(DI ~ R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.r2n..mor.bio = c(CU ~ R2n,LI ~ R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..mor.r2n..mor.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..r2n.bio..mor.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12  ,  LI ~ B1 + B4 + B7 + B12),
  d.bio..mor.r2n.bio..mor.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.bio..mor.r2n.bio..mor.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12, LI ~ B1 + B4 + B7 + B12),
  
#Consider always R2n but not C2n
  #only variables, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.r2n..d.mor..d.bio..mor.bio  = c(DI ~ R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio.mor.r2n..mor.bio = c(CU ~ R2n, LI ~ R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..mor.r2n..mor.bio = c(DI ~ R2n, CU ~ R2n ,  LI ~ R2n, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..r2n.bio..mor.bio  = c(DI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.mor..d.bio..mor.r2n.bio..mor.bio = c(CU ~ R2n ,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),
  d.r2n..d.mor..d.bio..mor.r2n.bio..mor.bio = c(DI ~ R2n, CU ~ R2n,  LI ~ R2n, R2n ~ B1 + B4 + B7 + B12, DI ~ CU + LI, DI ~ B1 + B4 + B7 + B12, CU ~ B1 + B4 + B7 + B12,  LI ~ B1 + B4 + B7 + B12),

#Consider always C2n but not R2n
#only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  #d.2n  = c(DI ~ C2n),
  rmor.2n = c(RCU ~C2n,RLI ~C2n),
  d.2n..rmor.2n = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n),
  d.2n..2n.rbio  = c(DI ~C2n, C2n ~ RB4),
  rmor.2n.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4),
  d.2n..rmor.2n.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4),
   
#Consider always C2n but not R2n
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.rmor  = c(DI ~C2n,DI ~ RCU + RLI),
  d.rmor..rmor.2n = c(RCU ~C2n,RLI ~C2n,DI ~ RCU + RLI),
  d.2n..d.rmor..rmor.2n = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n,DI ~ RCU + RLI),
  d.2n..d.rmor..2n.rbio  = c(DI ~C2n, C2n ~ RB4,DI ~ RCU + RLI),
  d.rmor..rmor.2n.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI),
  d.2n..d.rmor..rmor.2n.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI),
  
#Consider always C2n but not R2n
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.rbio  = c(DI ~C2n, DI ~ RB4),
  d.rbio..rmor.2n = c(RCU ~C2n,RLI ~C2n, DI ~ RB4),
  d.2n..d.rbio..rmor.2n = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, DI ~ RB4),
  d.2n..d.rbio..2n.rbio  = c(DI ~C2n, C2n ~ RB4, DI ~ RB4),
  d.rbio..rmor.2n.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, DI ~ RB4),
  d.2n..d.rbio..rmor.2n.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, DI ~ RB4),
  
#Consider always C2n but not R2n
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.2n..d.rmor..d.rbio  = c(DI ~C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.2n = c(RCU ~C2n,RLI ~C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.2n..d.rmor..d.rbio..rmor.2n = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n,DI ~ RCU + RLI, DI ~ RB4),
  d.2n..d.rmor..d.rbio..2n.rbio  = c(DI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.rmor..d.rbio..rmor.2n.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  d.2n..d.rmor..d.rbio..rmor.2n.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4),
  
#Consider always C2n but not R2n
 #only rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..rmor.rbio  = c(DI ~C2n, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.2n..rmor.rbio = c(RCU ~C2n,RLI ~C2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..rmor.2n..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..2n.rbio..rmor.rbio  = c(DI ~C2n, C2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  rmor.2n.rbio..rmor.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..rmor.2n.rbio..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
   
#Consider always C2n but not R2n
  #only rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.rmor..rmor.rbio  = c(DI ~C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.2n..rmor.rbio = c(RCU ~C2n,RLI ~C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..rmor.2n..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..2n.rbio..rmor.rbio  = c(DI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..rmor.2n.rbio..rmor.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..rmor.2n.rbio..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, RCU ~ RB4  ,  RLI ~ RB4),
  
#Consider always C2n but not R2n
   #only rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.rbio..rmor.rbio  = c(DI ~C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.2n..rmor.rbio = c(RCU ~C2n,RLI ~C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rbio..rmor.2n..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rbio..2n.rbio..rmor.rbio  = c(DI ~C2n, C2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rbio..rmor.2n.rbio..rmor.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rbio..rmor.2n.rbio..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  
#Consider always C2n but not R2n
  #only rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.2n..d.rmor..d.rbio..rmor.rbio  = c(DI ~C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.2n..rmor.rbio = c(RCU ~C2n,RLI ~C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..d.rbio..rmor.2n..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..d.rbio..2n.rbio..rmor.rbio  = c(DI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.rmor..d.rbio..rmor.2n.rbio..rmor.rbio = c(RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4),
  d.2n..d.rmor..d.rbio..rmor.2n.rbio..rmor.rbio = c(DI ~C2n, RCU ~C2n ,  RLI ~C2n, C2n ~ RB4,DI ~ RCU + RLI, DI ~ RB4, RCU ~ RB4  ,  RLI ~ RB4), 

 #variables and rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  #d.b2n  = c(DI ~ C2n + R2n),
  bmor.b2n = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n),
  d.b2n..bmor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n),
  d.b2n..b2n.bbio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12),
  bmor.b2n.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..bmor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12),
   
  
  #variables and rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.bmor  = c(DI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI),
  d.bmor..bmor.b2n = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI),
  d.b2n..d.bmor..bmor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI),
  d.b2n..d.bmor..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI),
  d.bmor..bmor.b2n.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI),
  d.b2n..d.bmor..bmor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI),
  
 
   #variables and rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.bbio  = c(DI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.bbio..bmor.b2n = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..bmor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.bbio..bmor.b2n.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..bmor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12),
  
 
  #variables and rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, no direct effect of bio on morphological rates
  d.b2n..d.bmor..d.bio  = c(DI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..d.bbio..bmor.b2n = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..bmor.b2n = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..b2n.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..d.bbio..bmor.b2n.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..bmor.b2n.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12),

  
 #variables and rates, no direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..bmor.bio  = c(DI ~ C2n + R2n, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  bmor.b2n..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..bmor.b2n..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..b2n.bbio..bmor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  bmor.b2n.bbio..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..bmor.b2n.bbio..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
 

  #variables and rates, direct effect of morphological rates on diversification, no direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.bmor..bmor.bio  = c(DI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..bmor.b2n..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..bmor.b2n..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n,  LI ~ C2n + R2n, RLI ~ C2n + R2n,DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..b2n.bbio..bmor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..bmor.b2n.bbio..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..bmor.b2n.bbio..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12,DI ~ CU + RCU + LI + RLI, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12, LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  

   #variables and rates, no direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.bbio..bmor.bio  = c(DI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bbio..bmor.b2n..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n,LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..bmor.b2n..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..b2n.bbio..bmor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12  ,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bbio..bmor.b2n.bbio..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bbio..bmor.b2n.bbio..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12, LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  

  #variables and rates, direct effect of morphological rates on diversification, direct effect of bio on diversification, direct effect of bio on morphological rates
  d.b2n..d.bmor..d.bbio..bmor.bio  = c(DI ~ C2n + R2n, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..d.bbio.bmor.b2n..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n, LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..bmor.b2n..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..b2n.bbio..bmor.bio  = c(DI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.bmor..d.bbio..bmor.b2n.bbio..bmor.bio = c(CU ~ C2n + R2n, RCU ~ C2n + R2n ,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),
  d.b2n..d.bmor..d.bbio..bmor.b2n.bbio..bmor.bio = c(DI ~ C2n + R2n, CU ~ C2n + R2n, RCU ~ C2n + R2n,  LI ~ C2n + R2n, RLI ~ C2n + R2n, R2n ~ B1 + B4 + RB4 + B7 + B12, C2n ~ B1 + B4 + RB4 + B7 + B12, DI ~ CU + RCU + LI + RLI, DI ~ B1 + B4 + RB4 + B7 + B12, CU ~ B1 + B4 + RB4 + B7 + B12, RCU ~ B1 + B4 + RB4 + B7 + B12,  LI ~ B1 + B4 + RB4 + B7 + B12, RLI ~ B1 + B4 + RB4 + B7 + B12),    

  .common = c()
  
  )




models3$d.2n

plot(models3$d.2n)

plot_model_set(models3)

result3 <- phylo_path(models3, data = my_data2, tree = my_tree, model = 'lambda', na.rm = TRUE)

result3

(s3 <- summary(result3))
plot(s3)

(best_model3 <- best(result3))


plot(best_model3)

average_model3 <- average(result3)
average_model3
plot(average_model3, algorithm = 'mds', curvature = 0.2) # increase the curvature to avoid overlapping edges

average_model_full3 <- average(result3, avg_method = "full")
average_model_full3
plot(average_model_full3, algorithm = 'mds', curvature = 0.2)





```



Let's create shuffle trees for the permutation analyses

```{r}

library(picante)
my_tree

my_trees <- list()

for (i in 1:100) my_trees[[i]] <- tipShuffle(my_tree)

my_trees

for (i in 1:100) write.tree(my_trees[[i]], paste0("./trees/my_tree", paste(i), ".tree"))

```


Let's get the matrices

```{r}

branchmatrix <- read.csv(file= "branch_matrix.csv")
branchmatrix
colnames(branchmatrix) <- c("div", "spe", "ext", "r2n")

branchmatrixsim <- matrix(0, 1508, 100)
for (i in 1:100) branchmatrixsim[,i] <- read.csv(paste0("./branchmatrix/branch_matrix", paste(i), ".csv"))[,2]

branchmatrixdef <- cbind(branchmatrix,branchmatrixsim)
dim(branchmatrixdef)

results <- list()
for (i in 5:105) results[[i-4]] <- summary(lm(branchmatrixdef[,1] ~ branchmatrixdef[,i]))

pvalues <- vector()
for (i in 1:100) pvalues[i] <- results[[i]]$coefficients[2,4]
pvalues

rsquareds <- vector()
for (i in 1:100) rsquareds[i] <- results[[i]]$r.squared
rsquareds

sort(pvalues)
summary(lm(branchmatrixdef[,1] ~ branchmatrixdef[,4]))$coefficients[2,4]
sort(rsquareds)
summary(lm(branchmatrixdef[,1] ~ branchmatrixdef[,4]))$r.squared

```


Plotting Quasse results

```{r}
load("./run1/.RData")
    #printing results. Best model OU.hump.sigmoid, so hump speciation and sigmoid extinction
    states.seq <- seq(min(states),max(states)) #Create a vector for the range of states
    chrom.mle.d.h.s #Look for the $par values, that are fully explained in $par.full
    #Those parameters will make the functions

 library(diversitree)

    mu.s <- sigmoid.x(states.seq, chrom.mle.d.h.s$par[5],chrom.mle.d.h.s$par[6],chrom.mle.d.h.s$par[7],chrom.mle.d.h.s$par[8])
    plot(states.seq, mu.s, type = "l")

 

    lambda.h <- noroptimal.x(states.seq, chrom.mle.d.h.s$par[1], chrom.mle.d.h.s$par[2], chrom.mle.d.h.s$par[3], chrom.mle.d.h.s$par[4])
    plot(states.seq, lambda.h, type = "l")

 

    div <- lambda.h - mu.s
    plot(states.seq, div, type = "l")
    
```

